[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'bhurlow/vim-parinfer'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'cespare/vim-toml'

