[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'eraserhd/parinfer-rust'
build = 'cargo build --release'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'jpalardy/vim-slime'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'hattya/license.vim'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'junegunn/fzf'
#path = '$HOME/.fzf'
#build = './install --all'

[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'janko-m/vim-test'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'def-lkb/ocp-indent-vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
