[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'eraserhd/parinfer-rust'
build = 'cargo build --release'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'jpalardy/vim-slime'
