hook global BufOpenFile .* %{
    evaluate-commands modeline-parse
}
hook global BufCreate .* %{ evaluate-commands editorconfig-load }
def ide %{
    rename-client main
    set global jumpclient main

    new rename-client tools
    set global toolsclient tools

    new rename-client docs
    set global docsclient docs
}
